#!/bin/sh
##### Run by cron

if [ -z "${source_rc_confs_defined}" ] ; then
    if [ -r /etc/defaults/rc.conf ] ; then
        . /etc/defaults/rc.conf
        source_rc_confs
    elif [ -r /etc/rc.conf ] ; then
        . /etc/rc.conf
    fi
fi

. /etc/rc.subr

if checkyesno klms_enable ; then
    sleep 300
    /usr/local/etc/rc.d/klms restart
    sleep 5
    /usr/bin/make -f /etc/mail/Makefile restart
    /usr/bin/logger -p mail.warn "Kaspersky Security for Linux Mail servers restarted after 5min-uptime."
else
    /usr/bin/logger -p mail.warn "KLMS not restarted."
fi

###########################################################################
